/*CONCAT USO PARA JUNTAR AS SUBSTRINGS QUE ACABEI DE 
EDITAR(COLOCO UM NUMERO DE ONDE VOU INICIAR, EM SEQUENCIA DIGO QUANTOS CARACTERES ELE VAI USAR)*/

SELECT CONCAT(
        SUBSTRING(cpf, 1, 3), '.',
        SUBSTRING(cpf, 4, 3), '.',
        SUBSTRING(cpf, 7, 3), '-',
        SUBSTRING(cpf, 10, 2)
    ) AS cpf_Formatted
FROM natural_person;