@startuml - Casos de Uso "Sistema Basico de Saude"
title Casos de Uso - RF02 - Cadastrar Unidades de Atendimento

"Secretário Municipal de Saúde" as Sec

Sec -> (Acessar Sistema)
(Acessar Sistema) -> (Cadastrar Unidade de Atendimento)

(Cadastrar Unidade de Atendimento) ---> (Validar Dados) : <<include>>
(Validar Dados) -> (Confirmar Cadastro) : <<include>>

@enduml