@startuml - Casos de Uso "Sistema Basico de Saude"
title Casos de Uso - RF03 - Cadastrar Pacientes

actor Fun as "Funcionário da Unidade"

Fun -> (Acessar Sistema)
(Acessar Sistema) -> (Cadastrar Paciente)

(Cadastrar Paciente) -up-> (Validar Dados) : <<include>>
(Validar Dados) -> (Confirmar Cadastro) : <<include>>

@enduml