Algoritmo "Combinações"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2023
Var
// Seção de Declarações das variáveis 
   c1, c2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para c1 <- 1 ate 3 faca
       Para c2 <- 1 ate 3 faca
        Escreva(c1, c2)
       Fimpara
   Fimpara

Fimalgoritmo