Algoritmo "Contador2.0"
//  Utilizando o Para...Proximo
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2023
Var
// Seção de Declarações das variáveis 
   cont : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   Para cont <- 10 Ate 1 Passo -1 Faca

        Escreva(cont)

   Fimpara






Fimalgoritmo
